#!/usr/bin/env bash
# Start the gitdocs API and the web dev server together, with a stable dev token.
#
#   ./scripts/dev.sh              build the libraries, seed if empty, then run both
#   ./scripts/dev.sh --no-build   skip the library build (fastest restart)
#   ./scripts/dev.sh --no-seed    never write demo content
#   ./scripts/dev.sh --reset      throw away the generated dev token and secret
#   ./scripts/dev.sh --port 4100  run the API on another port

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEV_ENV_FILE="$ROOT/.data/dev.env"
WEB_PORT="${GITDOCS_WEB_PORT:-5173}"

DO_BUILD=1
DO_SEED=1
DO_RESET=0
API_PORT=""

while [ $# -gt 0 ]; do
  case "$1" in
    --no-build) DO_BUILD=0 ;;
    --no-seed) DO_SEED=0 ;;
    --reset) DO_RESET=1 ;;
    --port) API_PORT="${2:?--port needs a value}"; shift ;;
    -h|--help) sed -n '2,9p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'; exit 0 ;;
    --) ;; # `pnpm dev -- --no-seed` forwards the separator itself
    *) echo "dev.sh: unknown option $1" >&2; exit 2 ;;
  esac
  shift
done

# --- colours -----------------------------------------------------------------
if [ -t 1 ]; then
  BOLD=$'\033[1m'; DIM=$'\033[2m'; CYAN=$'\033[36m'; GREEN=$'\033[32m'; YELLOW=$'\033[33m'; OFF=$'\033[0m'
else
  BOLD=""; DIM=""; CYAN=""; GREEN=""; YELLOW=""; OFF=""
fi
say() { printf '%s\n' "$*"; }
die() { printf '%s\n' "${YELLOW}dev.sh: $*${OFF}" >&2; exit 1; }

[ -d "$ROOT/node_modules" ] || die "dependencies are missing. Run: pnpm install"

random_hex() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex "$1"
    return
  fi
  node -e "process.stdout.write(require('node:crypto').randomBytes($1).toString('hex'))"
}

# --- environment -------------------------------------------------------------
# A project .env still wins for anything the developer set on purpose.
if [ -f "$ROOT/.env" ]; then
  set -a; . "$ROOT/.env"; set +a
fi

[ "$DO_RESET" -eq 1 ] && rm -f "$DEV_ENV_FILE"

mkdir -p "$ROOT/.data"

# Generated once, then reused, so the token stays valid across restarts and you
# can paste it into an MCP config or a curl alias and forget about it.
if [ ! -f "$DEV_ENV_FILE" ]; then
  {
    echo "# Generated by scripts/dev.sh. Delete this file to rotate the values."
    echo "GITDOCS_DEV_TOKEN=dev_$(random_hex 16)"
    echo "GITDOCS_DEV_SESSION_SECRET=$(random_hex 32)"
  } > "$DEV_ENV_FILE"
  chmod 600 "$DEV_ENV_FILE"
fi
set -a; . "$DEV_ENV_FILE"; set +a

export GITDOCS_CONTENT_DIR="${GITDOCS_CONTENT_DIR:-$ROOT/.data/content}"
export GITDOCS_PORT="${API_PORT:-${GITDOCS_PORT:-4000}}"
export GITDOCS_API_TOKENS="${GITDOCS_API_TOKENS:-$GITDOCS_DEV_TOKEN}"
export GITDOCS_PASSWORD="${GITDOCS_PASSWORD:-dev}"
export GITDOCS_SESSION_SECRET="${GITDOCS_SESSION_SECRET:-$GITDOCS_DEV_SESSION_SECRET}"
export GITDOCS_SEARCH_DB="${GITDOCS_SEARCH_DB:-$ROOT/.data/search.db}"
export GITDOCS_GIT_BRANCH="${GITDOCS_GIT_BRANCH:-main}"
export GITDOCS_AUTOCOMMIT_MS="${GITDOCS_AUTOCOMMIT_MS:-5000}"
# No remote in dev, so a background pull would only add noise.
export GITDOCS_AUTOPULL_MS="${GITDOCS_AUTOPULL_MS:-0}"
# apps/web/vite.config.ts proxies /api and /_assets to this URL.
export GITDOCS_API_URL="${GITDOCS_API_URL:-http://localhost:$GITDOCS_PORT}"

mkdir -p "$GITDOCS_CONTENT_DIR"

# --- build the libraries the server imports ----------------------------------
if [ "$DO_BUILD" -eq 1 ]; then
  say "${DIM}building workspace libraries...${OFF}"
  pnpm -r --sequential --filter '!@gitdocs/web' build
fi

# --- seed demo content on a first run ----------------------------------------
if [ "$DO_SEED" -eq 1 ] && [ -z "$(find "$GITDOCS_CONTENT_DIR" -mindepth 2 -name '_space.yml' -print -quit 2>/dev/null)" ]; then
  say "${DIM}content dir is empty, seeding demo content...${OFF}"
  pnpm exec tsx "$ROOT/scripts/seed.ts" --dir "$GITDOCS_CONTENT_DIR"
fi

# --- banner ------------------------------------------------------------------
cat <<BANNER

  ${BOLD}gitdocs dev${OFF}
  ${DIM}--------------------------------------------------------------${OFF}
  web UI      ${CYAN}http://localhost:${WEB_PORT}${OFF}
  REST API    ${CYAN}http://localhost:${GITDOCS_PORT}/api/v1${OFF}
  health      ${CYAN}http://localhost:${GITDOCS_PORT}/api/v1/health${OFF}
  content     ${DIM}${GITDOCS_CONTENT_DIR}${OFF}

  login password   ${GREEN}${GITDOCS_PASSWORD}${OFF}
  API token        ${GREEN}${GITDOCS_API_TOKENS}${OFF}

  ${DIM}curl -H "Authorization: Bearer \$GITDOCS_API_TOKENS" \\
    http://localhost:${GITDOCS_PORT}/api/v1/tree${OFF}
  ${DIM}--------------------------------------------------------------${OFF}

BANNER

exec pnpm exec concurrently \
  --kill-others \
  --names server,web \
  --prefix-colors blue,magenta \
  "pnpm --filter @gitdocs/server dev" \
  "pnpm --filter @gitdocs/web dev"
